### ISSUE TITLE
Will this add-on be on the new Extension Platform?

### ISSUE THREAD

**Issue by Dangry98** [oRazeD/UVToolkit#2]
Hi, are there any plans to add this amazing add-on to the new Blender Extension Platform?
https://extensions.blender.org/

**Comment by oRazeD** [comment]
Hey Dangry, I'm not the original creator of the tool so I have no idea if the blender foundation would appreciate me submitting the codebase. I may reach out to see if I can do such a thing

**Comment by Dangry98** [comment]
Hi @oRazeD, it seems fine to upload Forks, I just got 2 forks of other add-ons approvde :) As long as you follow this:
![image](https://github.com/user-attachments/assets/25ae3bb3-479a-467e-85ff-dfc86ad532ba)

**Comment by oRazeD** [comment]
Alright, I have some other personal add-ons I need to add to Extensions so I'll handle this when I do those. Thanks for bringing this up!

**Comment by Dangry98** [comment]
Awesome! Thank you :)

**Comment by Dangry98** [comment]
Hi, are there any news on this? 

PS, GrabDoc will need to be set to "Awaiting Review" in order to get reviews again, and hopfuly approvde on the extension platform! https://extensions.blender.org/approval-queue/grabdoc/
![image](https://github.com/user-attachments/assets/0787255d-6ad0-4662-a395-ebf7b73561a6)

**Comment by oRazeD** [comment]
The webpage already says it was set to "Awaiting Review", but I posted another comment with your instructions.... Hopefully it helps.

**Comment by oRazeD** [comment]
I updated my GrabDoc submission with everything they've asked for, but I've still run into one more issue I hope they can assist in resolving. Once GrabDoc is approved, I'll immediately do the same steps I did here to get it on the platform. Thanks for your patience!

https://extensions.blender.org/approval-queue/grabdoc/#activity-3259

**Comment by Dangry98** [comment]
Thank you! And hope the review proccese will go along a bit smoother from now one :)

**Comment by Dangry98** [comment]
> I updated my GrabDoc submission with everything they've asked for, but I've still run into one more issue I hope they can assist in resolving. Once GrabDoc is approved, I'll immediately do the same steps I did here to get UVToolkit on the extensions platform. Thanks for your patience!
> 
> https://extensions.blender.org/approval-queue/grabdoc/#activity-3259

Hi, I made a fixed version, seems that the folder path in get_version was wrong, now it start up with no errors! :) 
[GrabDoc.zip](https://github.com/user-attachments/files/16830303/GrabDoc.zip)

**Comment by Dangry98** [comment]
And do not forget that the add-on also needs a icon and at least one preview image to get accepted

**Comment by oRazeD** [comment]
Thanks for this, I got stuck here because the error code it gave was kind enough to not return an actual traceback. The code also worked in my development environment.

**Comment by oRazeD** [comment]
Since GrabDoc seems 99% of the way there, I modified UVToolkit to support the extensions system [0dbc47a](https://github.com/oRazeD/UVToolkit/commit/0dbc47a50df229998e617ed73c0c012570339819) and submitted the add-on to the extensions program.

https://extensions.blender.org/approval-queue/uv-toolkit/

**Comment by Dangry98** [comment]
> Since GrabDoc seems 99% of the way there, I modified UVToolkit to support the extensions system [0dbc47a](https://github.com/oRazeD/UVToolkit/commit/0dbc47a50df229998e617ed73c0c012570339819) and submitted the add-on to the extensions program.
> 
> https://extensions.blender.org/approval-queue/uv-toolkit/

Yay! 🥳 🎊 Thank you so much! Thats awsome! 😄 Going to be great once its available! You are doing important work for the community!

**Comment by oRazeD** [comment]
Closing this as UV Toolkit is now available on the extensions program.

https://extensions.blender.org/add-ons/uv-toolkit/
